### ISSUE TITLE
"Video covers/thumbnails no longer appear"

### ISSUE THREAD

**Issue by holta** [iiab/calibre-web#161]
Thanks @EMG70 for the bug report.

Let's start by investigating confirming / reproducing / debugging on Ubuntu 24.10 VM's.

**Comment by holta** [comment]
Confirmed on 10.8.0.10 here: (freshly installed 24.10 VM with the latest IIAB Calibre-Web)

![image](https://github.com/iiab/calibre-web/assets/2458907/fc0551a5-2c4a-4d87-b5e7-07e5cbe44639)

**Comment by holta** [comment]
@EMG70 noticed that this used to work, e.g. on LRN2.ORG here:

![image](https://github.com/iiab/calibre-web/assets/2458907/d3f00ca0-7df7-4c37-960c-319d020061f2)

**Comment by holta** [comment]
@deldesir explains:

> The cover issue [appears to be] caused by a regression in xklb. `--write-thumbnail` argument is no longer recognized as a valid one.

**Comment by deldesir** [comment]
I take back what I've said. --write-thumbnail does work on xklb. I wrongly debugged the issue by interpreting an error I received because I ommited --video option in lb dl command, sorry.
https://github.com/chapmanjacobd/library/blob/4b316e34253068016baee3d1e95373dcdd92392f/xklb/mediadb/download.py#L87

**Comment by holta** [comment]
Thanks @deldesir for explaining 💯

**Comment by deldesir** [comment]
I noticed the thumbnail file is downloaded outside of the video directory created upon download (_Youtube/<video_directory>_) and it's named after the `video_id`. It may be an xklb or yt-dlp regression. I am still investigating.

**Comment by holta** [comment]
> thumbnail file is downloaded outside of the video directory created upon download (_Youtube/<video_directory>_)

Any chance this new behavior is... intentional?

**Comment by holta** [comment]
@deldesir please close this issue within the coming week, if all looks solid!

- PR #162

**Comment by chapmanjacobd** [comment]
Ah yeah this is because the file is moved after:

- https://github.com/yt-dlp/yt-dlp/issues/6521#issuecomment-2105606176
- https://github.com/chapmanjacobd/library/commit/9f5a8be83b8d0224d8763094040b439410f82c55

Since you've already made a fix I think I'll leave this as-is but I might need to change it in the future if something else is broken by this, in which case just take out one of the `os.path.dirname`s

**Comment by holta** [comment]
> Since you've already made a fix

We can refine PR #162, no worries!

e.g. if thumbnails and sub-title files [ETC!] can always appear in the same directory with the original video, if that turns out to be an option?

(Anyway that would be my 1st choice, if @chapmanjacobd thinks that's a sensible long-term solution with yt-flp and xlkb?!)

**Comment by holta** [comment]
Thanks @chapmanjacobd for clarifying the underlying root cause:

- ytdl-org/youtube-dl#29912

(It sounds like he &/or @deldesir will try to restore the original behavior sometime soon — such that cover/thumbnail/poster once again appears in the very same directory as the video — so long as any excessively long path/filename is avoided with a very high degree of certainty!)

**Comment by holta** [comment]
Appears to be solved, with PR #162 refined by:

- PR #163
